---
- name: Ensure mako config directory exists
  ansible.builtin.file:
    path: "/home/{{ current_user }}/.config/mako"
    state: directory
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: '0755'

- name: Copy config files
  ansible.builtin.copy:
    src: .
    dest: "/home/{{ current_user }}/.config/mako/"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: '0644'
