general {
    # What command to run when the system asks to lock (e.g., loginctl lock-session)
    lock_cmd = pidof hyprlock || hyprlock -c $HOME/.config/hypr/hyprlock/hyprlock.conf
    
    # Lock the screen before the system goes to sleep
    before_sleep_cmd = pidof hyprlock || hyprlock -c $HOME/.config/hypr/hyprlock/hyprlock.conf
    
    # Turn on the display immediately after waking up
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' 
}

# 1. DIM SCREEN (e.g., after 2.5 minutes)
listener {
    timeout = 150
    # '-s' saves the current brightness, then sets it to 10%
    on-timeout = brightnessctl -s set 10%
    # '-r' restores the brightness to the saved value
    on-resume = brightnessctl -r
}

# 2. LOCK SCREEN (e.g., after 5 minutes)
listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock -c $HOME/.config/hypr/hyprlock/hyprlock.conf
}

# 3. TURN OFF SCREEN (e.g., after 6.5 minutes)
listener {
    timeout = 390
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}