- name: Install ly
  ansible.builtin.package:
    name:
      - ly
    state: present
  become: true

- name: Enable and start ly@tty2
  ansible.builtin.systemd:
    name: ly@tty2
    enabled: true
    state: started
  become: true
