---
- name: Ensure target configuration directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.vim/colors"
    state: directory
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: '0755'

- name: Copy Vim configuration file to target destination physically
  ansible.builtin.copy:
    src: ".vimrc"
    dest: "/home/{{ current_user }}/"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: '0644'


- name: Copy Vim themes files to target destination physically
  ansible.builtin.copy:
    src: "colors/"
    dest: "/home/{{ current_user }}/.vim/colors/"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: '0644'
