[General]
# Path to the wallpaper.
background=assets/background.jpg

# Material You-like colors
primaryColor=#D8DEE9
accentColor=#81A1C1
autoColor=true
use24HourClock=true
backgroundColor=#2E3440
textColor=#ECEFF4

# Font settings
fontFamily=Google Sans Flex
fontSize=12
